/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class LocalAsrEngine */

#ifndef _Included_LocalAsrEngine
#define _Included_LocalAsrEngine
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     LocalAsrEngine
 * Method:    AsrEngineInit
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_unisound_aios_audiocheck_JNI_LocalAsrEngine_AsrEngineInit
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     LocalAsrEngine
 * Method:    AsrEngineCheck
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_unisound_aios_audiocheck_JNI_LocalAsrEngine_AsrEngineCheck
  (JNIEnv *, jobject, jbyteArray, jstring, jstring);

/*
 * Class:     LocalAsrEngine
 * Method:    AsrGrammarBuild
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_unisound_aios_audiocheck_JNI_LocalAsrEngine_AsrGrammarBuild
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     LocalAsrEngine
 * Method:    AsrGrammarRefresh
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_unisound_aios_audiocheck_JNI_LocalAsrEngine_AsrGrammarRefresh
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LocalAsrEngine
 * Method:    AsrEngineRecognThresold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_unisound_aios_audiocheck_JNI_LocalAsrEngine_AsrEngineRecognizeThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     LocalAsrEngine
 * Method:    AsrEngineLoggerLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_unisound_aios_audiocheck_JNI_LocalAsrEngine_AsrEngineLoggerLevel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
